In [1]:
print("this is a string with an{}". format("insert"))

this is a string with aninsert


In [2]:
print("first object:{a},second:{b}". format(a=1,b=2.1))

first object:1,second:2.1


In [3]:
import sys
sys.version

'3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]'

In [7]:
name="ravi"
print(f"he said his name is {name}")

he said his name is ravi


In [11]:
m_list=[99,77,88]
m_list

[99, 77, 88]

In [13]:
m_list[0]=101
m_list

[101, 77, 88]

In [14]:
len(m_list)

3

In [18]:
m_list=m_list+["hai"]
m_list

[101, 77, 88, '1214511', '1214511', 1214511, 'hai']

In [19]:
m_list.pop()


'hai'

In [20]:
dictnry={'key1':777,'key2':8888}
dictnry['key2']

8888

In [1]:
print("how many apples you eat")
amnt=input()
print("ohh thats great such amount of apples eat "+amnt)

how many apples you eat
10
ohh thats great such amount of apples eat 10


In [4]:
print("enter the numbers to find greatest")
num1=input()
num2=input()
num3=input()
if (num1>num2 and num1>num3):
    print(num1)
elif(num2>num3 and num2>num1):
        print(num2)
else:
    print(num3)

enter the numbers to find greatest
555
20
10
555


In [19]:
print("enter the two numbers")
a=input()
b=input()
res = int(a) - int(b)
print(res)

enter the two numbers
20
10
10


In [20]:
a=input()
b=input()
res = int(a) * int(b)
print(res)

1
20
20


In [2]:
##list comprehensions
lst=[x for x in 'word']
lst

['w', 'o', 'r', 'd']

In [5]:
range(0,11)


range(0, 11)

In [12]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [68]:
##functions
## syntax def name of the function(arg1,arg2)
def sqr(x):
    return x**2


sqrt=print(sqr(5))



25


In [69]:
help(list.append)
    

Help on method_descriptor:

append(...)
    L.append(object) -> None -- append object to end



In [91]:
def is_prime(num):
    for n in range(2,num):
        if num % n ==0:
            print(num,'is not prime')
            break
        else:
            print(num,'is prime')
            break

In [93]:
is_prime(17)

17 is prime


In [98]:
##lambda expression map and filters
lambda num:num**2
print('square of ',square(2))

square of  4


In [ ]:
n1=int(input())
n2=int(input())
if n1 > n2:
    print('the greatest number is ',n1)
else:
    print('the greatest number is',n2)
    
    


10
50
the greatest number is 50


In [ ]:
num1=int(input())
print(num1)


In [9]:
num1=int(input())
num2=int(input())
reslt=num1*num2
print(reslt)


10
20
200


In [5]:
##working with dictionaries
my_dict={}

In [7]:
##working with the NumPy library for data analys
##if not installed inyour sysytem just type 
#conda install NumPy
import numpy as np

In [9]:
## creating a NumPy arrays
# from a python list 
my_list=[1,2,3]
np.array(my_list)

array([1, 2, 3])

In [11]:
mtrx=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mtrx)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
## np of zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((2,3))*2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [26]:
##linspace
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
#shape vector

In [34]:
np.random.rand(2)

array([0.07790033, 0.55624796])

In [36]:
np.random.randint(0,100,10)

array([22,  1, 80, 36, 69, 55, 60, 59, 45, 40])

In [39]:
np.random.rand(1,100)

array([[0.43823328, 0.10872948, 0.13778379, 0.59882168, 0.98101659,
        0.37708742, 0.87761203, 0.23342473, 0.17322549, 0.9345285 ,
        0.42218179, 0.54312832, 0.70150213, 0.60636704, 0.19236498,
        0.18340107, 0.04998047, 0.91873585, 0.38186748, 0.4093548 ,
        0.02185207, 0.75447228, 0.32386426, 0.78786962, 0.28337415,
        0.05818787, 0.89049943, 0.93084412, 0.31019718, 0.40624896,
        0.78477408, 0.59960422, 0.19368869, 0.31165041, 0.52032907,
        0.22266623, 0.37800771, 0.67554774, 0.39697947, 0.87569103,
        0.18506355, 0.46830397, 0.58513066, 0.43188565, 0.07209285,
        0.98596408, 0.62802529, 0.37266719, 0.500261  , 0.90364138,
        0.37652506, 0.83822641, 0.53138035, 0.43648489, 0.04814537,
        0.25173061, 0.6345447 , 0.94692038, 0.3225801 , 0.80742398,
        0.99932301, 0.57122799, 0.97040479, 0.74934707, 0.37023694,
        0.07896897, 0.77215683, 0.44392671, 0.48400168, 0.98913023,
        0.05269674, 0.02157421, 0.90168552, 0.94

In [43]:
np.random.randint(1,100)

84

In [45]:
#Array Attributes and Methods
arr=np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
#NumPy indexing and selecton
# create a samole arry
arr=np.arange(0,11)


In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#bracket indexing and selection
arr[5]

5

In [53]:
#get the values in a range
arr[1:5]

array([1, 2, 3, 4])

In [54]:
# broadcarsing
#setting a value with the index range
arr[0:5]=100

In [55]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr1=arr[0:6]
arr1

array([1, 2, 3, 4, 5, 6])

In [64]:
arr1[:]=99
arr1

array([99, 99, 99, 99, 99, 99])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [66]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [2]:
import numpy as np

In [3]:
arr=np.arange(1,11)

In [5]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [7]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
x=4
arr[arr>x]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
import numpy as np
import pandas as pd

In [26]:
from numpy.random import randn
np.random.seed(101)

In [27]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(), columns='W X Y Z'.split())

In [28]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [36]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [39]:
type(df['W'])

pandas.core.series.Series

In [41]:
## adding new data to the dataframe
df['new']=df['W']+df['Y']

In [42]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [44]:
##Drop the column in dataframe
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [53]:
#how to access only rows 
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [56]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [58]:
#if u want to acess the subset of dataframe
df.loc['B','Y']

-0.8480769834036315

In [60]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [1]:
df.iloc[[0,1],[2,3]]

NameError: name 'df' is not defined

In [7]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [8]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(), columns='W X Y Z'.split())

In [10]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [13]:
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [14]:
df[df["W"]>0]["Y"]

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [25]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
# Dealng with the missing values

df=pd.DataFrame({'A':[1,2,np.nan],
                'B':[5,np.nan,np.nan],
                'c':[1,2,3]})

In [27]:
df

A    B  c
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [55]:
df.dropna(axis=0)

A    B  c
0  1.0  5.0  1

In [53]:
df.dropna(thresh=2)

A    B  c
0  1.0  5.0  1
1  2.0  NaN  2

In [33]:
#fill the values in the na places
df.fillna(value='2.0')

A    B  c
0    1    5  1
1    2  2.0  2
2  2.0  2.0  3

In [34]:
#fillthe values with mean of the column
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [35]:
df

A    B  c
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [49]:
df['A'].fillna(value=df['c'].mean())

0    1.0
1    2.0
2    2.0
Name: A, dtype: float64

In [42]:
df1

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64